version: '2'

services:

  db:
    image: mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD : root
        MYSQL_DATABASE: senior_db
        MYSQL_USER: standalone
        MYSQL_PASSWORD: pno9i'g8kirT'=k9b
  web:
    command: bash -c "while ! nc -w 1 -z db 3306; do sleep 0.1; done; chmod +x manage.py migrate; while :; do ./manage.py runserver 0.0.0.0:8000; sleep 1; done"
    image: django
    build: .
    volumes:
      - .:/code
    depends_on:
      - db
    environment:
      IN_DOCKER: 1

  webserver:
    image: jumanjiman/caddy
    depends_on:
      - web
    ports:
      - "8000:8000"
    command: -port 8000 -host 0.0.0.0 "proxy / web:8000 { }"