# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-14 17:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DateExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_exam', models.CharField(max_length=256)),
                ('time_period', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'ตารางวันที่สอบ',
            },
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major_name', models.CharField(max_length=1024)),
            ],
            options={
                'verbose_name_plural': 'ตารางแขนง',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_years', models.IntegerField(default=0)),
                ('proj_semester', models.IntegerField(default=1)),
                ('proj_name_th', models.CharField(max_length=1024)),
                ('proj_name_en', models.CharField(max_length=1024)),
                ('proj_major', models.CharField(max_length=1024)),
                ('proj_advisor', models.CharField(max_length=1024)),
                ('proj_co_advisor', models.CharField(max_length=1024)),
            ],
            options={
                'verbose_name_plural': 'ตาราง โปรเจค',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=1024)),
            ],
            options={
                'verbose_name_plural': 'ตาราง ห้อง',
            },
        ),
        migrations.CreateModel(
            name='ScheduleRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_group', models.IntegerField(default=0)),
                ('date_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database_management.DateExam')),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_management.Room')),
            ],
            options={
                'verbose_name_plural': 'ตารางกำหนดการ',
            },
        ),
        migrations.CreateModel(
            name='ScoreAdvisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propose', models.IntegerField(default=0)),
                ('planning', models.IntegerField(default=0)),
                ('tool', models.IntegerField(default=0)),
                ('advice', models.IntegerField(default=0)),
                ('improve', models.IntegerField(default=0)),
                ('quality_report', models.IntegerField(default=0)),
                ('quality_project', models.IntegerField(default=0)),
                ('proj_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_management.Project')),
            ],
            options={
                'verbose_name_plural': 'ตาราง คะแนนที่ปรึกษา',
            },
        ),
        migrations.CreateModel(
            name='ScorePoster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_spo', models.IntegerField(default=0)),
                ('character_spo', models.IntegerField(default=0)),
                ('presentation_spo', models.IntegerField(default=0)),
                ('question_spo', models.IntegerField(default=0)),
                ('media_spo', models.IntegerField(default=0)),
                ('quality_spo', models.IntegerField(default=0)),
                ('proj_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_management.Project')),
            ],
            options={
                'verbose_name_plural': 'ตาราง คะแนนโพสเตอร์',
            },
        ),
        migrations.CreateModel(
            name='ScoreProj',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentation_media', models.IntegerField(default=0)),
                ('presentation', models.IntegerField(default=0)),
                ('question', models.IntegerField(default=0)),
                ('report', models.IntegerField(default=0)),
                ('discover', models.IntegerField(default=0)),
                ('analysis', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('levels', models.IntegerField(default=0)),
                ('quality', models.IntegerField(default=0)),
                ('proj_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_management.Project')),
            ],
            options={
                'verbose_name_plural': 'ตาราง คะแนนโปรเจค',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=1024)),
                ('proj_group_exam', models.IntegerField(default=0)),
                ('proj_group_poster', models.IntegerField(default=0)),
                ('levels_teacher', models.IntegerField(default=1)),
                ('login_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('major_teacher', models.ManyToManyField(to='database_management.Major')),
                ('score_advisor', models.ManyToManyField(to='database_management.ScoreAdvisor')),
                ('score_posters', models.ManyToManyField(to='database_management.ScorePoster')),
                ('score_projs', models.ManyToManyField(to='database_management.ScoreProj')),
            ],
            options={
                'ordering': ['login_user'],
                'verbose_name_plural': 'ตาราง อาจารย์',
            },
        ),
        migrations.CreateModel(
            name='TimeExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_exam', models.CharField(max_length=256)),
                ('time_period', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'ตารางเวลา',
            },
        ),
        migrations.AddField(
            model_name='scheduleroom',
            name='time_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database_management.TimeExam'),
        ),
        migrations.AddField(
            model_name='dateexam',
            name='room_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database_management.Room'),
        ),
    ]
