# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_management', '0003_auto_20171115_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduleroom',
            name='teacher_group',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='proj_group_exam',
        ),
    ]
