# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 09:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_management', '0005_auto_20171115_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='proj_group_exam',
        ),
    ]
