# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-22 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database_management', '0007_remove_scheduleroom_date_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleroom',
            name='date_id',
           field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database_management.DateExam'),
        ),
    ]
