# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-23 09:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database_management', '0008_scheduleroom_date_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='login_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
