# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-24 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database_management', '0011_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.IntegerField(default=0)),
                ('student_name', models.CharField(max_length=1024)),
                ('proj_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database_management.Project')),
            ],
            options={
                'verbose_name_plural': 'ตาราง คะแนนที่ปรึกษา',
            },
        ),
        migrations.AlterField(
            model_name='settings',
            name='activate',
            field=models.IntegerField(default=1),
        ),
    ]
