# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-24 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_management', '0012_auto_20180125_0057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'ตาราง นักศึกษา'},
        ),
    ]
