# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-15 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_management', '0014_auto_20180215_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='proj_group_exam',
            field=models.IntegerField(default=0),
        ),
    ]
