# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-18 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_management', '0015_teacher_proj_group_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='proj_group_exam',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='proj_group_poster',
        ),
    ]
