# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-03-20 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_management', '0016_auto_20180318_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='measure_spost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='measure_sproj',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='levels_teacher',
            field=models.IntegerField(default=0),
        ),
    ]
