# Generated by Django 2.0.3 on 2018-04-03 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database_management', '0019_auto_20180321_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='proj_id',
        ),
        migrations.AddField(
            model_name='student',
            name='proj1_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='database_management.Project'),
        ),
        migrations.AddField(
            model_name='student',
            name='proj2_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='database_management.Project'),
        ),
    ]
