# Generated by Django 2.0.3 on 2018-04-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_management', '0020_auto_20180403_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_name',
        ),
        migrations.AddField(
            model_name='student',
            name='first_name',
            field=models.CharField(default='', editable=False, max_length=1024),
        ),
        migrations.AddField(
            model_name='student',
            name='last_name',
            field=models.CharField(default='', editable=False, max_length=1024),
        ),
        migrations.AddField(
            model_name='student',
            name='pre_name',
            field=models.CharField(default='', editable=False, max_length=1024),
        ),
    ]
