# Generated by Django 2.0.3 on 2018-04-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_management', '0021_auto_20180411_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='pre_name',
        ),
        migrations.AddField(
            model_name='student',
            name='student_name',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
