# Generated by Django 2.0.3 on 2018-04-11 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database_management', '0022_auto_20180411_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='schedule_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scheduleroom',
            name='proj_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database_management.Project'),
        ),
    ]
