# Generated by Django 2.0.3 on 2018-04-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_management', '0023_auto_20180411_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='schedule_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
