# Generated by Django 2.0.3 on 2018-04-14 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_management', '0026_teacher_proj_group_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='proj_group_exam',
        ),
    ]
