# Generated by Django 2.0.3 on 2018-04-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_management', '0027_remove_teacher_proj_group_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleroom',
            name='semester',
            field=models.IntegerField(default=1),
        ),
    ]
