# Generated by Django 2.0.3 on 2018-04-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_management', '0028_scheduleroom_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='load_post',
            field=models.IntegerField(default=8),
        ),
        migrations.AlterField(
            model_name='settings',
            name='load',
            field=models.IntegerField(default=8),
        ),
    ]
