# Generated by Django 2.0.3 on 2018-04-24 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database_management', '0029_auto_20180423_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulePoster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_post', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name_plural': 'ตารางกำหนดการโปสเตอร์',
            },
        ),
        migrations.AlterModelOptions(
            name='scheduleroom',
            options={'verbose_name_plural': 'ตารางกำหนดการโปรเจค'},
        ),
        migrations.AddField(
            model_name='project',
            name='sche_post_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='load_post',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='scheduleposter',
            name='proj_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='database_management.Project'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='schepost_teacher',
            field=models.ManyToManyField(to='database_management.SchedulePoster'),
        ),
    ]
